# Generated by Django 3.1.1 on 2020-10-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_year', models.PositiveIntegerField(default=0, max_length=4)),
                ('album_length', models.FloatField(default=0.0, help_text='Album time in minutes.')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was view.', verbose_name='last played date at')),
            ],
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('TypeList', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('length', models.FloatField(default=0.0, help_text='track time in minutes.')),
                ('views', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=2)),
                ('song_year', models.PositiveIntegerField(default=0, max_length=4)),
                ('record_company', models.CharField(blank=True, max_length=100)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.artist')),
            ],
        ),
        migrations.CreateModel(
            name='TypeList',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField(default=0)),
                ('musiclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.musiclist')),
                ('musictrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.musictrack')),
            ],
        ),
    ]
