# Generated by Django 3.1.1 on 2020-10-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('album_title', models.CharField(blank=True, max_length=100)),
                ('album_year', models.PositiveIntegerField(default=0)),
                ('album_length', models.FloatField(default=0.0, help_text='Album time in minutes.')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100)),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('fuente_id', models.CharField(blank=True, max_length=100)),
                ('fuente_uri', models.URLField(blank=True)),
                ('fuente_img', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('listened_uri', models.URLField(blank=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was view.', verbose_name='last played date at')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('type_list', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.CharField(max_length=100)),
                ('uri', models.URLField(blank=True)),
                ('length', models.FloatField(default=0.0, help_text='track time in minutes.')),
                ('views', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=2)),
                ('song_year', models.PositiveIntegerField(default=0)),
                ('record_company', models.CharField(blank=True, max_length=100)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('tempo', models.IntegerField(default=0)),
                ('time_sig', models.IntegerField(default=0)),
                ('key_of', models.CharField(blank=True, max_length=20)),
                ('camelot', models.CharField(blank=True, max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='laramusicAPI.album')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TypeList',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackInList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('visits', models.PositiveIntegerField(default=0)),
                ('musiclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.musiclist')),
                ('musictrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.musictrack')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musiclist',
            name='musictracks',
            field=models.ManyToManyField(through='laramusicAPI.TrackInList', to='laramusicAPI.MusicTrack'),
        ),
    ]
