# Generated by Django 3.1.1 on 2020-10-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laramusicAPI', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='musiclist',
            name='tracks',
            field=models.ManyToManyField(through='laramusicAPI.TrackInList', to='laramusicAPI.MusicTrack'),
        ),
        migrations.AddField(
            model_name='history',
            name='musictrack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.musictrack'),
        ),
        migrations.AddField(
            model_name='history',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laramusicAPI.artist'),
        ),
    ]
