# Generated by Django 3.1.1 on 2020-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laramusicAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musictrack',
            old_name='record_company',
            new_name='song_id',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
